# Generated by Django 4.0.3 on 2022-04-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='default_img.jpg', upload_to='profile_image'),
        ),
    ]
