# Generated by Django 4.0.3 on 2022-04-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_userprofile_geolocation_alter_userprofile_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='post_code',
            new_name='postal_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='geolocation',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
